BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-susan"
BBFILE_PATTERN_meta-susan = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-susan = "10"

LAYERDEPENDS_meta-susan = "core openembedded-layer networking-layer filesystems-layer"
LAYERRECOMMENDS_meta-susan = "mender"

LICENSE_PATH += "${LAYERDIR}/licenses"

LAYERSERIES_COMPAT_meta-susan = "scarthgap"
