# name type source persistent target
systemd-network dir /usr/lib/systemd/network /sudoagi/private/config/systemd-network /etc/systemd/network
hostname file /etc/hostname /sudoagi/private/config/hostname /etc/hostname
device-id file /etc/sudoagi/device-id /sudoagi/private/config/device-id /etc/sudoagi/device-id
ssh dir /etc/ssh /sudoagi/private/config/ssh /etc/ssh
